config/routes.rb
# frozen_string_literal: true

#
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

full_path_glob = "(/*full_path)"

# allow plugins to prepend routes
Dir[Rails.root.join("{gems,vendor}/plugins/*/config/pre_routes.rb")].each do |pre_routes|
  load pre_routes
end

CanvasRails::Application.routes.draw do
  post "/api/graphql", to: "graphql#execute"
  post "/api/graphql/subgraph", to: "graphql#subgraph_execute"
  # The subgraph endpoint is for use only with the federated API Gateway. See
  # `app/graphql/README.md` for details.
  get "graphiql", to: "graphql#graphiql"

  resources :submissions, only: [] do
    resources :submission_comments, path: :comments, only: :index, defaults: { format: :pdf }
    resources :docviewer_audit_events, only: [:create], constraints: { format: :json }
  end
  resources :submission_comments, only: [:update, :destroy]

  resources :epub_exports, only: [:index]

  get "inbox" => "context#inbox"
  get "oauth/redirect_proxy" => "oauth_proxy#redirect_proxy"

  get "conversations/unread" => "conversations#index", :as => :conversations_unread, :redirect_scope => "unread"
  get "conversations/starred" => "conversations#index", :as => :conversations_starred, :redirect_scope => "starred"
  get "conversations/sent" => "conversations#index", :as => :conversations_sent, :redirect_scope => "sent"
  get "conversations/archived" => "conversations#index", :as => :conversations_archived, :redirect_scope => "archived"
  get "conversations/find_recipients" => "search#recipients"

  get "search/recipients" => "search#recipients"
  post "conversations/mark_all_as_read" => "conversations#mark_all_as_read"
  get "conversations/batches" => "conversations#batches", :as => :conversation_batches
  resources :conversations, only: %i[index show update create destroy] do
    post :add_recipients
    post :add_message
    post :remove_messages
  end

  post "/external_auth_observers/redirect_login" => "login/external_auth_observers#redirect_login", :as => :external_auth_validation

  # So, this will look like:
  # http://instructure.com/register/5R32s9iqwLK75Jbbj0
  match "register/:nonce" => "communication_channels#confirm", :as => :registration_confirmation, :via => [:get, :post]
  # deprecated
  get "pseudonyms/:id/register/:nonce" => "communication_channels#confirm", :as => :registration_confirmation_deprecated
  post "confirmations/:user_id/re_send(/:id)" => "communication_channels#re_send_confirmation", :as => :re_send_confirmation, :id => nil
  get "confirmations/:user_id/limit_reached(/:id)" => "communication_channels#confirmation_limit_reached", :as => :confirmation_limit_reached, :id => nil
  match "forgot_password" => "pseudonyms#forgot_password", :as => :forgot_password, :via => [:get, :post]
  get "pseudonyms/:pseudonym_id/change_password/:nonce" => "pseudonyms#confirm_change_password", :as => :confirm_change_password
  post "pseudonyms/:pseudonym_id/change_password/:nonce" => "pseudonyms#change_password", :as => :change_password

  # callback urls for oauth authorization processes
  get "oauth" => "users#oauth"
  get "oauth_success" => "users#oauth_success"

  get "mr/:id" => "info#message_redirect", :as => :message_redirect
  get "help_links" => "info#help_links"

  # This is a debug route that makes working on error pages easier
  get "test_error" => "info#test_error" unless Rails.env.production?
  get "live_events/heartbeat" => "info#live_events_heartbeat" unless Rails.env.production?

  concern :question_banks do
    resources :question_banks do
      post :bookmark
      post :reorder
      get :questions
      post :move_questions
      resources :assessment_questions
    end
  end

  concern :groups do
    resources :groups, except: :edit
    resources :group_categories, only: %i[create update destroy]
    get "group_unassigned_members" => "groups#unassigned_members"
  end

  resources :group_categories do
    member do
      post "clone_with_name"
    end
  end

  concern :files do
    resources :files, except: [:new] do
      get "inline" => "files#text_show", :as => :text_inline
      get "download" => "files#show", :download => "1"
      get "download.:type" => "files#show", :as => :typed_download, :download => "1"
      get "preview" => "files#show", :preview => "1"
      post "inline_view" => "files#show", :inline => "1"
      get "contents" => "files#attachment_content", :as => :attachment_content
      get "file_preview" => "file_previews#show"
      collection do
        get "folder#{full_path_glob}" => "files#react_files", :format => false, :defaults => { format: "html" }
        get "search" => "files#react_files", :format => false, :defaults => { format: "html" }
        get :quota
        post :reorder
      end
      get "*file_path" => "files#show_relative", :as => :relative_path, :file_path => /.+/ # needs to stay below react_files route
    end
  end

  concern :file_images do
    get "images" => "files#images"
  end

  concern :relative_files do
    get "file_contents/*file_path" => "files#show_relative", :as => :relative_file_path, :file_path => /.+/
  end

  concern :folders do
    resources :folders
  end

  concern :media do
    get "media_download" => "users#media_download"
  end

  concern :users do
    get "users" => "context#roster"
    get "user_services" => "context#roster_user_services"
    get "users/:user_id/usage" => "context#roster_user_usage", :as => :user_usage
    get "users/:id" => "context#roster_user", :as => :user
  end

  concern :announcements do
    resources :announcements
    post "announcements/external_feeds" => "announcements#create_external_feed"
    delete "announcements/external_feeds/:id" => "announcements#destroy_external_feed", :as => :announcements_external_feed
  end

  concern :discussions do
    resources :discussion_topics, only: %i[index new show edit destroy]
    get "discussion_topics/:id/*extras" => "discussion_topics#show", :as => :map, :extras => /.+/
    resources :discussion_entries
  end

  concern :pages do
    resources :wiki_pages, path: :pages, except: %i[update destroy new], constraints: { id: %r{[^/]+} } do
      get "revisions" => "wiki_pages#revisions", :as => :revisions
    end

    get "wiki" => "wiki_pages#front_page", :as => :wiki
    get "wiki/:id" => "wiki_pages#show_redirect", :id => %r{[^/]+}
    get "wiki/:id/revisions" => "wiki_pages#revisions_redirect", :id => %r{[^/]+}
    get "wiki/:id/revisions/:revision_id" => "wiki_pages#revisions_redirect", :id => %r{[^/]+}
  end

  concern :conferences do
    resources :conferences do
      match :join, via: [:get, :post]
      match :close, via: [:get, :post]
      get :recording
      delete :recording, to: "conferences#delete_recording", as: :delete_recording
      get :settings
    end
  end

  get "/courses/:course_id/gradebook2", to: redirect("/courses/%{course_id}/gradebook")

  # There are a lot of resources that are all scoped to the course level
  # (assignments, files, wiki pages, user lists, forums, etc.).  Many of
  # these resources also apply to groups and individual users.  We call
  # courses, users, groups, or even accounts in this setting, "contexts".
  # There are some helper methods like the before_filter :get_context in application_controller
  # and the application_helper method :context_url to make retrieving
  # these contexts, and also generating context-specific urls, easier.
  resources :courses do
    # DEPRECATED
    get "self_enrollment/:self_enrollment" => "courses#self_enrollment", :as => :self_enrollment
    post "self_unenrollment/:self_unenrollment" => "courses#self_unenrollment", :as => :self_unenrollment
    post :unconclude
    get :students
    get "observer_pairing_codes.csv", action: :observer_pairing_codes_csv, as: "observer_pairing_codes"
    post :enrollment_invitation
    # this needs to come before the users concern, or users/:id will preempt it
    get "users/prior" => "context#prior_users", :as => :prior_users
    concerns :users
    get :statistics
    delete "unenroll/:id" => "courses#unenroll_user", :as => :unenroll
    post "move_enrollment/:id" => "courses#move_enrollment", :as => :move_enrollment
    delete "unenroll/:id.:format" => "courses#unenroll_user", :as => :formatted_unenroll
    post "limit_user_grading/:id" => "courses#limit_user", :as => :limit_user_grading
    delete "conclude_user/:id" => "courses#conclude_user", :as => :conclude_user_enrollment
    post "unconclude_user/:id" => "courses#unconclude_user", :as => :unconclude_user_enrollment
    resources :sections, except: %i[index edit new] do
      get "crosslist/confirm/:new_course_id" => "sections#crosslist_check", :as => :confirm_crosslist
      post :crosslist
      delete "crosslist" => "sections#uncrosslist", :as => :uncrosslist
    end

    get "undelete" => "context#undelete_index", :as => :undelete_items
    post "undelete/:asset_string" => "context#undelete_item", :as => :undelete_item

    get "settings#{full_path_glob}", action: :settings
    get :settings
    get "details" => "courses#settings"
    post :re_send_invitations
    post :enroll_users
    post :link_enrollment
    post :update_nav
    resource :gradebook do
      get "submissions_upload/:assignment_id" => "gradebooks#show_submissions_upload", :as => :show_submissions_upload

app/controllers/content_exports_controller.rb
# frozen_string_literal: true

#
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
#

class ContentExportsController < ApplicationController
  include K5Mode

  before_action :require_permission, except: :xml_schema
  before_action { |c| c.active_tab = "settings" }

  def require_permission
    get_context
    @context ||= @current_user # if we're going through the dashboard
    return render_unauthorized_action unless @context&.grants_all_rights?(@current_user, :read, :read_as_admin)
  end

  def index
    scope = @context.content_exports_visible_to(@current_user).without_epub
    @exports = scope.active.not_for_copy.order("content_exports.created_at DESC")
    @current_export_id = scope.running.first.try(:id)
  end

  def show
    if params[:id].present? && (export = @context.content_exports_visible_to(@current_user).where(id: params[:id]).first)
      render_export(export)
    else
      render json: { errors: { base: t("errors.not_found", "Export does not exist") } }, status: :not_found
    end
  end

  def create
    export = @context.content_exports_visible_to(@current_user).running.first
    if export
      # an export is already running, just return it
      render_export(export)
    else
      export = @context.content_exports.build
      export.user = @current_user
      export.workflow_state = "created"

      case @context
      when Course
        if params[:export_type] == "qti"
          export.export_type = ContentExport::QTI
          export.selected_content = params[:copy].to_unsafe_h
        else
          export.export_type = ContentExport::COMMON_CARTRIDGE
          export.selected_content = { everything: true }
        end
      when User
        export.export_type = ContentExport::USER_DATA
      end

      export.progress = 0
      if export.save
        export.export
        render_export(export)
      else
        render json: { error_message: t("errors.couldnt_create", "Couldn't create content export.") }
      end
    end
  end

  def destroy
    if params[:id].present? && (export = @context.content_exports_visible_to(@current_user).where(id: params[:id]).first)
      export.destroy
      render json: { success: "true" }
    else
      render json: { errors: { base: t("errors.not_found", "Export does not exist") } }, status: :not_found
    end
  end

  def xml_schema
    if (filename = CC::Schema.for_version(params[:version]))
      cancel_cache_buster
      send_file(filename, type: "text/xml", disposition: "inline")
    else
      render "shared/errors/404_message", status: :not_found, formats: [:html]
    end
  end

  private

  def render_export(export)
    json = export.as_json(only: %i[id progress workflow_state], methods: [:error_message])
    json["content_export"]["download_url"] = verified_file_download_url(export.attachment, export) if export.attachment && !export.expired?
    render json:
  end
end

app/views/content_exports/_quiz_export_checklist.html.erb
<%
# Copyright (C) 2012 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<fieldset>
  <legend><%= t :select_quizzes, "Select Quizzes to Export" %></legend>
    <div style="overflow: auto; max-height: 200px">
    <%= check_box :copy, :all_quizzes, :class => "copy_all", :checked => true %><%= label :copy, :all_quizzes, t('labels.all_quizzes', "All Quizzes") %>
    <ul class="unstyled_list" style="margin-<%= direction('left') %>: 20px;">
      <% global_ids = @context.content_exports.temp_record.can_use_global_identifiers? %>
      <% @context.quizzes.active.each do |quiz| %>
        <li>
          <%= check_box "copy[quizzes]", mig_id(quiz, global: global_ids), :class => 'quiz_item', :checked => true %>
          <%= label "copy[quizzes]", mig_id(quiz, global: global_ids), quiz.title %>
        </li>
      <% end %>
    </ul>
  </div>
</fieldset>

app/views/content_exports/index.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<%
  title = @context.is_a?(Course) ? t('content_exports', "Content Exports") : t('user_data_exports', "Download Submissions")
  friendly_message = @context.is_a?(Course) ? nil : t("Creating a Submission Export will allow you to download a zip file of all your assignment submissions in all of your present and past courses. This could be a big file, so it may take a while. You can navigate away from the page and come back later.")
%>


<% add_crumb title %>
<% provide :page_title do %><%= title %><% end %>

<div>
  <h1><%= title %></h1>

  <% if friendly_message %>
    <p><%= friendly_message %></p>
  <% end %>

  <div class="export_messages" style="<%= hidden %>">
    <div class="alert-error error_message"></div>
  </div>

  <hr aria-hidden="true"/>

  <div id="export_files">
    <% @exports.each do |export| %>
      <% unless export.running? %>
        <% if export.workflow_state == 'exported' %>
          <p>
            <% date = "<span class=\"created_at time_ago_date\" data-timestamp=\"#{export.created_at.iso8601}\">#{datetime_string export.created_at}</span>".html_safe %>
            <% wrapper = link_to('\1', export.attachment ? verified_file_download_url(export.attachment) : nil) %>
            <% if export.expired? %>
              <%= t "Course Export from %{date} (file not available)", :date => date %>
            <% elsif export.export_type == ContentExport::COMMON_CARTRIDGE %>
              <%= t "*Course Export from %{date}*", :date => date, :wrapper => wrapper %>
            <% elsif export.export_type == ContentExport::QTI %>
              <%= t "*QTI Export from %{date}*", :date => date, :wrapper => wrapper %>
            <% elsif export.export_type == ContentExport::USER_DATA %>
              <%= t "*User Data Export from %{date}*", :date => date, :wrapper => wrapper %>
            <% elsif export.export_type == ContentExport::ZIP %>
              <%= t "*File Export from %{date}*", :date => date, :wrapper => wrapper %>
            <% end %>
          </p>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <% if ContentExport.expire? %>
    <p><em><%= t "Content export files cannot be downloaded after %{days} days.", days: ContentExport.expire_days %></em></p>
  <% end %>

  <hr aria-hidden="true"/>

  <div class="form" style="<%= hidden if @current_export_id %>">
    <% if @context.is_a?(Course) %>
      <%= form_tag course_content_exports_path(@context.id), :id => "exporter_form" do %>
        <fieldset>
          <h2><%= t :export_type, "Export Type" %></h2>
          <div>
            <input type="radio" name="export_type" value="common_cartridge" id="cc_export_radio" checked>
            <label for="cc_export_radio"><%= t 'labels.course', 'Course' %></label>
          </div>
          <div>
            <input type="radio" name="export_type" value="qti" id="qti_export_radio">
            <label for="qti_export_radio"><%= t 'labels.quiz', 'Quiz' %></label>
            <div id="quiz_selection" style="display:none;">
              <%= render :partial => 'quiz_export_checklist' %>
            </div>
          </div>
        </fieldset>
        <div>
          <button type="submit" class="submit_button btn btn-primary"><%= t 'buttons.create', "Create Export" %></button>
        </div>
        <div class="clear"></div>
      <% end %>
    <% elsif @context == @current_user %>
      <% if @current_user.submissions.exists? %>
        <%= form_tag dashboard_content_exports_path, :id => "exporter_form" do %>
          <div>
            <button type="submit" class="submit_button btn btn-primary"><%= t 'buttons.create', "Create Export" %></button>
          </div>
          <div class="clear"></div>
        <% end %>
      <% else %>
        <%= t('no_submissions', "You currently have no submissions to export.") %>
      <% end %>
    <% end %>
  </div>

  <div class="progress_bar_holder" style="<%= hidden unless @current_export_id %> margin-top: 10px;">
      <div class="export_progress"></div>
      <% if @context.is_a?(Course) %>
        <div class="progress_message">
          <%= mt 'message.export_started', "The export process has started. This can take a while for large courses. *You can leave the page* and you'll get an email when the export is complete." %>
        </div>
      <% end %>
  </div>

  <% if @current_export_id %>
    <div id="current_export_id" style="<%= hidden %>"><%= @current_export_id %></div>
  <% end %>
</div>

<% js_bundle :content_exports %>