config/routes.rb
# frozen_string_literal: true

#
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

full_path_glob = "(/*full_path)"

# allow plugins to prepend routes
Dir[Rails.root.join("{gems,vendor}/plugins/*/config/pre_routes.rb")].each do |pre_routes|
  load pre_routes
end

CanvasRails::Application.routes.draw do
  post "/api/graphql", to: "graphql#execute"
  post "/api/graphql/subgraph", to: "graphql#subgraph_execute"
  # The subgraph endpoint is for use only with the federated API Gateway. See
  # `app/graphql/README.md` for details.
  get "graphiql", to: "graphql#graphiql"

  resources :submissions, only: [] do
    resources :submission_comments, path: :comments, only: :index, defaults: { format: :pdf }
    resources :docviewer_audit_events, only: [:create], constraints: { format: :json }
  end
  resources :submission_comments, only: [:update, :destroy]

  resources :epub_exports, only: [:index]

  get "inbox" => "context#inbox"
  get "oauth/redirect_proxy" => "oauth_proxy#redirect_proxy"

  get "conversations/unread" => "conversations#index", :as => :conversations_unread, :redirect_scope => "unread"
  get "conversations/starred" => "conversations#index", :as => :conversations_starred, :redirect_scope => "starred"
  get "conversations/sent" => "conversations#index", :as => :conversations_sent, :redirect_scope => "sent"
  get "conversations/archived" => "conversations#index", :as => :conversations_archived, :redirect_scope => "archived"
  get "conversations/find_recipients" => "search#recipients"

  get "search/recipients" => "search#recipients"
  post "conversations/mark_all_as_read" => "conversations#mark_all_as_read"
  get "conversations/batches" => "conversations#batches", :as => :conversation_batches
  resources :conversations, only: %i[index show update create destroy] do
    post :add_recipients
    post :add_message
    post :remove_messages
  end

  post "/external_auth_observers/redirect_login" => "login/external_auth_observers#redirect_login", :as => :external_auth_validation

  # So, this will look like:
  # http://instructure.com/register/5R32s9iqwLK75Jbbj0
  match "register/:nonce" => "communication_channels#confirm", :as => :registration_confirmation, :via => [:get, :post]
  # deprecated
  get "pseudonyms/:id/register/:nonce" => "communication_channels#confirm", :as => :registration_confirmation_deprecated
  post "confirmations/:user_id/re_send(/:id)" => "communication_channels#re_send_confirmation", :as => :re_send_confirmation, :id => nil
  get "confirmations/:user_id/limit_reached(/:id)" => "communication_channels#confirmation_limit_reached", :as => :confirmation_limit_reached, :id => nil
  match "forgot_password" => "pseudonyms#forgot_password", :as => :forgot_password, :via => [:get, :post]
  get "pseudonyms/:pseudonym_id/change_password/:nonce" => "pseudonyms#confirm_change_password", :as => :confirm_change_password
  post "pseudonyms/:pseudonym_id/change_password/:nonce" => "pseudonyms#change_password", :as => :change_password

  # callback urls for oauth authorization processes
  get "oauth" => "users#oauth"
  get "oauth_success" => "users#oauth_success"

  get "mr/:id" => "info#message_redirect", :as => :message_redirect
  get "help_links" => "info#help_links"

  # This is a debug route that makes working on error pages easier
  get "test_error" => "info#test_error" unless Rails.env.production?
  get "live_events/heartbeat" => "info#live_events_heartbeat" unless Rails.env.production?

  concern :question_banks do
    resources :question_banks do
      post :bookmark
      post :reorder
      get :questions
      post :move_questions
      resources :assessment_questions
    end
  end

  concern :groups do
    resources :groups, except: :edit
    resources :group_categories, only: %i[create update destroy]
    get "group_unassigned_members" => "groups#unassigned_members"
  end

  resources :group_categories do
    member do
      post "clone_with_name"
    end
  end

  concern :files do
    resources :files, except: [:new] do
      get "inline" => "files#text_show", :as => :text_inline
      get "download" => "files#show", :download => "1"
      get "download.:type" => "files#show", :as => :typed_download, :download => "1"
      get "preview" => "files#show", :preview => "1"
      post "inline_view" => "files#show", :inline => "1"
      get "contents" => "files#attachment_content", :as => :attachment_content
      get "file_preview" => "file_previews#show"
      collection do
        get "folder#{full_path_glob}" => "files#react_files", :format => false, :defaults => { format: "html" }
        get "search" => "files#react_files", :format => false, :defaults => { format: "html" }
        get :quota
        post :reorder
      end
      get "*file_path" => "files#show_relative", :as => :relative_path, :file_path => /.+/ # needs to stay below react_files route
    end
  end

  concern :file_images do
    get "images" => "files#images"
  end

  concern :relative_files do
    get "file_contents/*file_path" => "files#show_relative", :as => :relative_file_path, :file_path => /.+/
  end

  concern :folders do
    resources :folders
  end

  concern :media do
    get "media_download" => "users#media_download"
  end

  concern :users do
    get "users" => "context#roster"
    get "user_services" => "context#roster_user_services"
    get "users/:user_id/usage" => "context#roster_user_usage", :as => :user_usage
    get "users/:id" => "context#roster_user", :as => :user
  end

  concern :announcements do
    resources :announcements
    post "announcements/external_feeds" => "announcements#create_external_feed"
    delete "announcements/external_feeds/:id" => "announcements#destroy_external_feed", :as => :announcements_external_feed
  end

  concern :discussions do
    resources :discussion_topics, only: %i[index new show edit destroy]
    get "discussion_topics/:id/*extras" => "discussion_topics#show", :as => :map, :extras => /.+/
    resources :discussion_entries
  end

  concern :pages do
    resources :wiki_pages, path: :pages, except: %i[update destroy new], constraints: { id: %r{[^/]+} } do
      get "revisions" => "wiki_pages#revisions", :as => :revisions
    end

    get "wiki" => "wiki_pages#front_page", :as => :wiki
    get "wiki/:id" => "wiki_pages#show_redirect", :id => %r{[^/]+}
    get "wiki/:id/revisions" => "wiki_pages#revisions_redirect", :id => %r{[^/]+}
    get "wiki/:id/revisions/:revision_id" => "wiki_pages#revisions_redirect", :id => %r{[^/]+}
  end

  concern :conferences do
    resources :conferences do
      match :join, via: [:get, :post]
      match :close, via: [:get, :post]
      get :recording
      delete :recording, to: "conferences#delete_recording", as: :delete_recording
      get :settings
    end
  end

  get "/courses/:course_id/gradebook2", to: redirect("/courses/%{course_id}/gradebook")

  # There are a lot of resources that are all scoped to the course level
  # (assignments, files, wiki pages, user lists, forums, etc.).  Many of
  # these resources also apply to groups and individual users.  We call
  # courses, users, groups, or even accounts in this setting, "contexts".
  # There are some helper methods like the before_filter :get_context in application_controller
  # and the application_helper method :context_url to make retrieving
  # these contexts, and also generating context-specific urls, easier.
  resources :courses do
    # DEPRECATED
    get "self_enrollment/:self_enrollment" => "courses#self_enrollment", :as => :self_enrollment
    post "self_unenrollment/:self_unenrollment" => "courses#self_unenrollment", :as => :self_unenrollment
    post :unconclude
    get :students
    get "observer_pairing_codes.csv", action: :observer_pairing_codes_csv, as: "observer_pairing_codes"
    post :enrollment_invitation
    # this needs to come before the users concern, or users/:id will preempt it
    get "users/prior" => "context#prior_users", :as => :prior_users
    concerns :users
    get :statistics
    delete "unenroll/:id" => "courses#unenroll_user", :as => :unenroll
    post "move_enrollment/:id" => "courses#move_enrollment", :as => :move_enrollment
    delete "unenroll/:id.:format" => "courses#unenroll_user", :as => :formatted_unenroll
    post "limit_user_grading/:id" => "courses#limit_user", :as => :limit_user_grading
    delete "conclude_user/:id" => "courses#conclude_user", :as => :conclude_user_enrollment
    post "unconclude_user/:id" => "courses#unconclude_user", :as => :unconclude_user_enrollment
    resources :sections, except: %i[index edit new] do
      get "crosslist/confirm/:new_course_id" => "sections#crosslist_check", :as => :confirm_crosslist
      post :crosslist
      delete "crosslist" => "sections#uncrosslist", :as => :uncrosslist
    end

    get "undelete" => "context#undelete_index", :as => :undelete_items
    post "undelete/:asset_string" => "context#undelete_item", :as => :undelete_item

    get "settings#{full_path_glob}", action: :settings
    get :settings
    get "details" => "courses#settings"
    post :re_send_invitations
    post :enroll_users
    post :link_enrollment
    post :update_nav
    resource :gradebook do
      get "submissions_upload/:assignment_id" => "gradebooks#show_submissions_upload", :as => :show_submissions_upload

app/helpers/files_helper.rb
# frozen_string_literal: true

#
# Copyright (C) 2023 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
module FilesHelper
  def load_media_object
    if params[:attachment_id].present?
      @attachment = Attachment.find_by(id: params[:attachment_id])
      @attachment = @attachment.context.attachments.find(params[:attachment_id]) if @attachment&.deleted?
      return render_unauthorized_action if @attachment&.deleted?
      return render_unauthorized_action unless @attachment&.media_entry_id

      @media_object = @attachment.media_object_by_media_id
      @media_object.current_attachment = @attachment unless @media_object.nil?
      @media_id = @media_object&.id
    elsif params[:media_object_id].present?
      @media_id = params[:media_object_id]
      @media_object = MediaObject.by_media_id(@media_id).take
    end
  end

  def check_media_permissions(access_type: :download)
    if @attachment.present?
      access_allowed(@attachment, @current_user, access_type)
    else
      media_object_exists = @media_object.present?
      render_unauthorized_action unless media_object_exists
      media_object_exists
    end
  end

  def access_allowed(attachment, user, access_type)
    if params[:verifier]
      verifier_checker = Attachments::Verification.new(attachment)
      return true if verifier_checker.valid_verifier_for_permission?(params[:verifier], access_type, session)
    end
    submissions = attachment.attachment_associations.where(context_type: "Submission").preload(:context)
                            .filter_map(&:context)
    return true if submissions.any? { |submission| submission.grants_right?(user, session, access_type) }
    return render_unauthorized_action if (access_type == :update) && attachment.editing_restricted?(:content)

    authorized_action(attachment, user, access_type)
  end
end

app/views/files/_nested_content.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<% skip_ul ||= false; exclude_files ||= false %>
<% unless skip_ul %><ul><% end %>
  <% folders ||= [] %>
  <% nested_content.compact.select{|i| !i.is_a?(Attachment) || !exclude_files}.each do |item|
    new_f = folders.to_a.find{|i| i.id == item.id} if folders && item.is_a?(Folder)
    item = new_f if new_f
    subcontent = folders.select{|f| f.parent_folder_id == f.id } if exclude_files && !folders.empty?
    subcontent ||= item.subcontent(:exclude_files => exclude_files) if item.respond_to?(:subcontent)
  %>
    <li class="<%= item.is_a?(Attachment) ? "file" : "folder" %> <%= 'folder_locked' if item.is_a?(Folder) && item.currently_locked %> <%= item.mime_class rescue "" %> <%= item.is_a?(Attachment) ? "file" : "folder" %>_<%= item ? item.id : "blank" %>">
      <span class="id" style="display: none;"><%= item.id %></span>
      <span class="text name"><%= item.display_name %></span>
      <% if subcontent %>
        <%= render :partial => "files/nested_content", :object => subcontent, :locals => {:exclude_files => exclude_files} %>
      <% end %>
    </li>
  <% end %>
<% unless skip_ul %></ul><% end %>

app/views/files/show.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<% provide :page_title do %>
  <%= join_title @attachment.display_name, @context&.name %>
<% end %>
<% add_crumb @attachment.display_name, context_url(@context, :context_file_url, @attachment) %>
<% download_url = context_url(@context, :context_file_download_url, @attachment.id, download_frd: 1, verifier: params[:verifier]) %>
<% js_bundle 'module_sequence_footer' %>
<% if (locked = @attachment.locked_for?(@current_user, :check_policies => true)) %>
  <div style="margin: 10px 50px;">
    <% if @attachment.folder && @attachment.folder.locked? %>
      <%= t 'messages.folder_locked', "The folder \"%{folder},\" which includes this file, has been locked.", :folder => @attachment.folder.name %>
    <% else %>
      <%= locked.is_a?(Hash) ? lock_explanation(locked, 'file', @context) : t('messages.file_locked', "This file has not been unlocked yet.") %>
    <% end %>
  </div>
<% else %>
  <h2><%= @attachment.display_name %></h2>
  <div>
    <span style="font-size: 1.2em;">
      <%= link_to "Download #{@attachment.display_name}", download_url, download: "true" %>
    </span> (<%= @attachment.readable_size %>)
  </div>
  <% if @attachment.content_type == "application/x-shockwave-flash" %>
    <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" class="embedded_swf">
      <param name="movie" value="<%= safe_domain_file_url(@attachment, fallback_url: download_url, verifier: params[:verifier]) %>" />
      <param name="wmode" value="transparent" />
      <param name="salign" value="t" />
      <param name="allowscriptaccess" value="never" />
      <!--[if !IE]>-->
      <object type="application/x-shockwave-flash" data="<%= safe_domain_file_url(@attachment, fallback_url: download_url, verifier: params[:verifier]) %>" class="embedded_swf">
        <param name="wmode" value="transparent" />
        <param name="salign" value="t" />
        <param name="allowscriptaccess" value="never" />
        <!--<![endif]-->
        <!--[if !IE]>-->
      </object>
      <!--<![endif]-->
    </object>
  <% elsif @attachment.inline_content? && !@attachment.canvadocable? %>
    <% js_bundle :file %>
    <iframe id="file_content" src="<%= safe_domain_file_url(@attachment, fallback_url: download_url, verifier: params[:verifier]) %>" style="width: 100%; height: 400px;" title="<%= t('File Content') %>"></iframe>
  <% elsif @attachment.content_type && @attachment.content_type.match(/\Aimage\//) %>
    <%= link_to(image_tag(download_url, :alt => @attachment.display_name), download_url) %>
  <% elsif @attachment.content_type && @attachment.content_type.match(/\Avideo\/|audio\//) %>
    <% js_bundle :file_preview %>
    <div id="media_preview" <%= media_preview_attributes(@attachment) %>></div>
  <% else %>
    <% js_bundle :file_show %>
    <div id="doc_preview" <%= doc_preview_attributes(@attachment) %>></div>
  <% end %>
<% end %>
<%= render :partial => 'shared/sequence_footer', :locals => {:asset => @attachment} %>